language: python
python:
- '3.6'
install:
- pip install ansible==2.9.7 'molecule[gce]<3' apache-libcloud
script:
- ls -la
- molecule test --scenario-name gce
after_script:
- molecule destroy --scenario-name gce
before_install:
- openssl aes-256-cbc -K $encrypted_3b9f0b9d36d1_key -iv $encrypted_3b9f0b9d36d1_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mv google_compute_engine /home/travis/.ssh/
- chmod 0600 /home/travis/.ssh/google_compute_engine
env:
  global:
  - USER=travis
