language: python
python:
- '3.6'
install:
- pip install molecule-gce ansible==2.9.7 molecule<3 apache-libcloud
script:
  - ls -la
  - molecule test --scenario-name gce
after_script:
  - molecule destroy --scenario-name gce
before_install:
  - openssl aes-256-cbc -K $encrypted_7b81dd4d66f3_key -iv $encrypted_7b81dd4d66f3_iv
    -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar
  - mv google_compute_engine /home/travis/.ssh/
  - chmod 0600 /home/travis/.ssh/google_compute_engine
env:
  global:
  - secure: O5PPseyAsNgnmUC3nOSTWmSHVRlokcfd4vktcI34r2RsVaq444RnxN/R7RHmSGHsR7czb/j9AoDZCiKmPfTGuy8sWeHWh8tBnY8wvIjCaT+exaZUb7QzCyB5UjYZwpP1HPU3g8FBPv7ht3Ijl2ExMnM/ql99qeRTpF+dtJq3VyJ6UU6KhbAYYOdLyBr09Cj96dT8KTXti1z13DmOvDjOcBhFWtsPeO7XwK5rdkNY7ZPEhpmmmVd9ZBFTeCoYQeP2tGd/tUrjD6hKylK7GXeX9Ko0VPb8Ebm2UpoNYN3itTttFht6oxVdJc/bnWwmpB+5Rtf/YN6B3Jgaw8Zvd7AzQsGAQKA+0qlavtF/kB7yVtHuOiiRWN9svZqHsnuT6WzdIo7SDmADQxMxsV61SChy5fu3GN+HSmqjGh31aDGAs3QcyFiHt3TDb9zlehw/atC5z4+9oK2xg8lrND/57tLuJwe8AXp0w24qZoYVpfhOut4bRGH2BbxS4FsEVf05Owx/b8J7oZewzh8WcWrJl8RaImAywtQOA3Y5iMQymIZbuX/FBj5LB+tljS4Clg7N3ehITCeEZJXvtLC7Rrb8Jzefn+ANJLKlhxmlHp44tZz0O9xc0M9Sbi/BerBWSe7yuXxj/c0dS0H7dLcZz+ZHEy6lwiHPltAQGwcvz8/YaJfW44c=
  - secure: nq86/6cguRHcihEejK+dJETAlCr+f2m5WhrsyHnnCGL090WTxYKdkXx7ol2xbXH3Lqzmn4+LhQ3X5UMiMuDBEPoVB0XxucVllgBxmlU7Pmmqi2eLkpqqGfjC0MvJwF/0T8YH9dC3GteciYRlW+i2MnW3kKKSkNetYr5y07B2C2G9pds+tIzrj3yhgDiiOOgiIp/4IWklsraBvVeUVNoVMNBLMKXrqZNTRSJTU15mnmrOPTNqrVCvMYV/vYUV1Fj0Db6gOYGeD4So5/g/8az+Hqg44Ve+d5V/0TLyUuRiMH91/OofZpiUHXjnxscWCh3megtGkDU9QXI7j0h1CJZaYS+nl8RGSKYkakMRFMX+gCWEErrfv6OSHE/9Lj85Nee/1yXQ1eERrC7NhXWb2nEA1S6mRJtDcdvMJ32q0SmyDi8OuHHVN9CU83qnZ+fK1yyRrYqjn7cmPBNaOd6y//03ShikZQof9nijYVplAg1PQtD5t5/AbBL0/T5ZXM3gw2zwaFyXT5vEkFS9aTR2jhoY0e0TFjvmLwYHlxDa0by9bihqS/AWRsok127ooRLAannaWtJYBZfyMq2eiXa7SB9X0tKvVVIRyMTfXGkcN3CFlfd5m+qH6vCfD5brF2dQreBx5w7Fo0w/hADxWjmTBmBPSK7JuzHFJ2PPy9QYmdcE+Fo=
  - secure: jCBNWviLKsiNV6zGgoD+is84fQoloy5iNdL5A2vfYDL+FwmRLMLubE3cgBwRU6xcHtVMmnDAuE2twlk5LAyTExFJe43vOHfIygTruKkQnBl0LojEYu8xTV0ykUvxakZosaRHqe5CdAlw+1gmlxVZYbnwkmOqBZMpgsr/yF1k6S8dLF05AM0HFYflwHtfUYJ+GfBoTOdYu52MvBX9GNz+W2JlUEBGAPbvLBPOVMCCtNX6ugzIPRHdixoP56y6AlnR/VKgwmeMq6q6Z8oC+amLkSfX6zYScJIYVGvAAC+wvOEQUjMmDXLeRRxCux30g4xNnG970/PP+kGXHNQE07ERMhit7gxpiGU+yLj3FrJxDTPuMSgxrVGrEKFEAdQdKglxWQOIJu6Eb1KZ/lRMlSaac8527kXLrURogTQQq/szYUv41+3PuuKPk1JH8aI57NLWnbAV0Q40Dga8x9DqQRplEP0jxOZnZqg3fYkviWNqvQ8EF8V1zz0pXTQFWsFWL5FcGN+tnEK5pqW8e+DgaGtPjKMKb4E4/grwHvfX6F6fhid3d0MZtMkVsuqhLjOZZJOIDt9ePzVVtYib3Hv3jlOfg4uwI0Fvql0emwtawHC+aWCY81vQuyXUGUDiLvbzgtTqjxRV/il5khK92dqNdWTJh6CkUGEe1MZx6S6b6IRFYKQ=
