language: python
python:
- '3.6'
install:
- pip install ansible==2.9.7 'molecule[gce]<3' 'apache-libcloud<3'
script:
- ls -la
- molecule test --scenario-name gce
after_script:
- molecule destroy --scenario-name gce
before_install:
- openssl aes-256-cbc -K $encrypted_3b9f0b9d36d1_key -iv $encrypted_3b9f0b9d36d1_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mv google_compute_engine /home/travis/.ssh/
- chmod 0600 /home/travis/.ssh/google_compute_engine
env:
  global:
  - USER=travis
  - secure: l9VB1HYucFn5Y9Fw7wJ316DIEwVNdLolXIZYEvBHYhLa3/OB1kWlbfUz4C26fPwmHmksCTP26UeZ3DvMYKwbiYSJ47B1Hk+XPQA6UgJ/5qrKvdspTsVKE9XE10+F/cDHrYRNeEkpoH081caynUTwOKbJMtn6Plwutx8DQL4VASIaibNM6CMpu/NG1oVSDnlcoBgyeg2mhkck31xoHqozXKpyOlkKOpqq8IADntMjoyLmpd8vK7I/FUr0yzJ9qR0Kep8BxdaTwjPA4GDue+dcD3WWBESik+cblQclNLF/VVZgroh3X9CtXWfWCBm0LxvXlxOTlcTGlOWCIj0TwSRLPOTZpkcYENfV9p3bxBLiiEXgqcjDfr9JSdidDQGfrkkkdSmXquVOK1RAOIYPvPaeBM69ZpVIwOxJyrTxPUVIWNUwdqKCm9lojVgGxY8nhkA65K+qkhj65a9Ceg9MddOeqSZNwX+FUwlwtXhWMFzMHm9NerZVVBufy5a98yze7t9FwqZSNDhqBxsB+5gWqhtyv8/h8Grra8QmNJSYJnL1hG2IIaPmX6ZyMSNRlkxBM0tsINBGufAxkSNTSGUHh+9tB2bFBRPfZeH9YWmFeG6bt8O91B7RCn7UBXb/qK8U4fioYlRKQsp3P8RQY0JnEmMhjKix9u8aSQt2y9o0TwUUfM8=
  - secure: FNaHTM7z09dxjj5NMIZItNTkS5W+xSHvnbXptJ34VbhjBOHdcbxY4W1DQAboqkLPVi49dswb7ulxosYIa7MAUD+argmOLM9AiVAaRGIMoPdRDR7fAIsQ3YKTLob7eXSXynLgNZMiTBN8ZJYl1fY/EujLI7iAzkGIH02LB39ovBTGm4z/pL8K0Ad+BcEO4tJ7hJtFQH5euqh44tfcWI10ZoSeLjp2+NqljeD4Y8pT+rwRZaZYTRvXHYZTrw3A3q5wJL1i/fTqEckQ3YV2I1OaBBDxM+66sVXtL9gNVVvFwViNaiv1mk46UOLPLjz4WGIyESfifv40SLNl9/o4DycZls7NREl2G9a1klaon0aa76nieVuR59P+QKKnVAfAl/8ugQ6Ri/bUSOFmXCrl2VxtpOjRc9/drOeaqB/EslxJCu+KdqqGapoKZmAZpdLCdOWmmao8/3oL74ZRLwrcOJBHTvC17s0tcWTS5oTM6+P1yZWehgyO+s+6qr+PGEqmtsQUG7Lrw6QaplHUI0ICRdy2i+8viI9WsP7MbdGE8pw2WCuYzYE884t3Rz3tdbzU1jDHugnIFTnEdR1BovyjyPbzX6PRrXOMsbTYp5Z+vZb5aTcdvR+7pzktBeVhZSL84nj75Z2WHlAmN+pP5P/AIiaa84XwtG+AAhKfqC5GANoRZaI=
  - secure: IKhui0lKQZuL3OOAZ6yVA3S4eC6huo4r6Y1wruiDV5WWv8tw8DM5+gaQrsEa7SHcAgrREAs2a5qFx6QZqaU+88/SDqpY20k6HitvDxjhudpE/yGBQ6cAfdgLBzwngprZUaakTwI/NxkBVEHuHMd60gpDA2ZQDVYl2329pIjcX9CFDdFYtF7PDXzwm1tP4s7735WonRGFUpCATVoqou0QY+wg1xBHEVnmlWKcBnYnng8pJY8QrwU+MgtjfqDj79MCODUtSBkMILfRsDGLenWuLnpMFkpAlnGK9P0+Ci1uUvebGKHsDGZRi1xcp8kW8PQmnbmR2IhaX9Bs+kjNCr1dOZ9rzg2iKE600Jayt63KpqW29iRUbupf72PQ++mzV8UWGvyM2KdfR0sLgM2dFRbf2J2ZzErqkPp2YmHGSJeqkOJPG5Q9XBU78crMiPsx//fpRVcsqZrh4EocQlhHf6BdX2VEGnt447yIZC2447QdU6CarFQqHz88nmJFgOdNMK+5TShfakKQ7OfFxLOCsnjWEeSjxl3zqQxz9THb+hrvUyX2tvIbbUZfa6XyR3bcGOWIP1P5iA3GjemdvWuI6+jFJBvdgJzQNr1f9Ey0JwtpargTBs42/8QHJaR4scjd32xLz30JSqgA0bSBrJ2LabyhHKla0JO1DDx44XJvs39z17Y=
