language: python
python:
- '3.6'
install:
- pip install ansible==2.9.7 'molecule[gce]<3' apache-libcloud
script:
- ls -la
- molecule test --scenario-name gce
after_script:
- molecule destroy --scenario-name gce
before_install:
- openssl aes-256-cbc -K $encrypted_3b9f0b9d36d1_key -iv $encrypted_3b9f0b9d36d1_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mv google_compute_engine /home/travis/.ssh/
- chmod 0600 /home/travis/.ssh/google_compute_engine
env:
  global:
  - USER=travis
  - secure: auKmE8k91+mEGa3O4WEBJuF+Hgp1H43WXbr/kVjYCvc8wMWxHt2PmTD7AkFpI5MuQen52SOBvFUcxjpID+AYevwKVpOAMYc2th7KvSNI65pi8LFtcMHqk4ZnRB3QRE7Etd0BIGQS4o5tYBaNm7ZoAE4jeIAHqDo5r2UpklgrMUFBp1X5fNE71gtshCa/dCDeidhDEMjswTDUICQlIdADjNW5fBVEI2tYRojjDF5iTP+7TEEIEM3TanoLeX0qOlnOy+sGL0vtTIjTT1L6LyU8n7dS54+TVp7Hzh3yZmbsrYZoKlf5xrU1Z3ldrShfgEfP0IFE+2DTHKGWniJqJIGGQ4dWoaxA6RQPccU7zl0/3QOxaDJrziwPzVC/6IDCkykW5ZR+d7vNQh9yCwBvspbeIAYUSNM/f4mkVPAVB9K3gG7OmozXxQ2H/6MFQ4pDwcIxfJ4Np/PY5nu1fOPpjoIcZ8uNMULAzb1B8OzuuIbqTimA4DBvUZDJYsz2tGb85FvLtt54te6xx5rd6aoguJ73axe8VmnQBNTzWMNlu81Tux45AtaN67C3wt3WXjGryAgNa0ZLF+H1gMVvv70SPWlA74haFhJ5MiiWTpTfr/O9sjzPAu0o6VpdBFVw2mcqfs2lwrRciArXT/vzbQeAMQEjMx+51SLA/D0UjlBUB7JobJU=
  - secure: UnSnm/R0QwuWeVsYDPOjNZGPzPpvS5Eo26FCmGWN6GYTpv9Y3kXrP75W6rEfs3hJjfLRcFfSDL3V9QxyqN4H4NwovzR+PcCmHoOE3kn2jDg/cVxiiOJ0v+WpEqq5nq+O/0X14VChGQCG4TRRL30USZgyOT9op+p9APpfCIpmCFRMj/i4sFrlKy8kXWmqV/BdwQLGno8ibRtgiNGd7Nx+q64CyLNsQg+EMdnfwbKq7nH/rjr2me/ToB9HjLZ5N/j6cEi4eG+RSwkJzpSCGUtZowBfNeelBxWRnvp5xftqbtS3L+t110dUQm/WiuDVnGMLNpLD+zW/oK5JdoILqey1QbWbE85XdqXHeXbGsRmdcfkoKRL61MyMOcXphhca2TEjQ4zZP9F1pga6vW9P8WL61rtr0TA0BUZM56+yNZvGq1hu98g3UuTGeYVHOLxwoBoUEeN2q187IKEXuX6lCiO1GvgYelbZV9e7zDaR8AKYd/UPDxLLagEAfzJFajUZ6t6YfbjeQDuL/lnxFO9Em9kHbR1pr8ySLyYmVnPYEplNT210M2Bw3LIyEYAjz3a5M5+x2BtCRsuvR1oz69zega//Wnl88bFIyYn+eNW6aJkSXrg9HuOngw5WKmnxeOoOhTdUcOX/Ebr066D3rqDBeDuoQk3O4nDLr047xWOPJM3GTvU=
  - secure: ciKWJAas5/aD2UrAS/4OfQSgh00dxwhJqITVxFXkWCiRppvjxSLu54wS7DidGXA5eiMA8Dq5zZX3WdFEj/P3P10XyGpmw4Oakk4yi+fChCmEk1TgGy66T5nx59eFPYOsU4RUO/luRyED0JvBDhgRYEwBjj7r3ZAHHTfXeq7TJWbMziX1BiPeQpWPXMP9Tdj8hOd3CnIqwgrZPxdxPIenWQ5mPWCqbr2xNkm+mAGh/gE1Xhp4oOC5MQtClVY7GOk7Epx2gnhEZYjdWUe0vXahVKsOYMwucUcPS/i4xEcfDyvJv8yw1yoqaz0H4WbSCC3TipdghKhnhntjjLcoBEQfWM+8VQoS8lyQP6qlfZdzTYouw2eA2asPe4dISFl/jfGuXEcy5KZ01buGgqo+XalI2xc5d1JMzcrYZDrQsUemG2NxV7FNBaMZL8B0phJZQ3n7jagyNpUYp0pvRrrSGC+p7j9gfnFTBy6VMztLMY3DZootxZ3NO4o1yardkSVujkW72jwzXAmDoxLBT71ahAWW7EpLXKbKQOlUD1mPTbp+56Dx8YZHWaGLsgWLCoA3y5ZVL7FILdZQjldpGFedVWys9K+C+EfcUESqVFCg3vgbcByoInsTI+xnFzO9QQrxKG3iWK1H1v6TPWy0uDP7ByB1V/EFXpWFwXXSI5y33WHu6bM=
