- name: Import MongoDB public GPG Key
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: 42F3E95A2C4F08279C4960ADD68FA50FEA312927
  tags: install

- name: Add MongoDB repository into sources list
  apt_repository:
    repo: deb http://repo.mongodb.org/apt/ubuntu {{ ansible_distribution_release }}/mongodb-org/3.2 multiverse
    state: present
  tags: install

- name: Install MongoDB package
  apt:
    name: mongodb-org
    update_cache: yes
  tags: install

- name: enable mongod
  systemd:
    name: mongod
    enabled: yes
  tags: install
